name: booboo USA
favicon: null
layout_spectrum: 0.3088025958277285
typography_spectrum: 0.7103892357554287
title: organise your world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
